import "@/app/_styles/globals.css";

export const metadata = {
  title: "Test Dango Front End Developer v2",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
